In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    res = sess.run(hello + world)

In [9]:
print(res)

b'Hello World'


In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [15]:
result

30

In [16]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4), 10)

In [19]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [21]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [23]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [24]:
sess = tf.InteractiveSession()

In [25]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.19504918  0.6717719  -0.42298505 -0.85355574]
 [ 0.09264192 -0.80800676 -0.54748803  0.29801127]
 [ 0.65504026 -0.6634623  -1.188371   -1.7591149 ]
 [ 0.37853324 -0.2784414  -0.14240608 -0.9550498 ]]


[[0.17269802 0.5141753  0.03113508 0.746933  ]
 [0.7160692  0.8340628  0.29736316 0.06921124]
 [0.66239035 0.22030413 0.22964203 0.85403395]
 [0.19239593 0.10381472 0.82601607 0.43818307]]




In [26]:
a = tf.constant([[1,2],
                [3,4]])

In [27]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [28]:
b = tf.constant([[10], [100]])

In [29]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [31]:
result = tf.matmul(a, b)

In [32]:
sess.run(result)

array([[210],
       [430]])

In [33]:
result.eval()

array([[210],
       [430]])